#!/bin/bash



 #run on all arguments starting from second argument
	# echo "this is running"
	# if [[ -d "$file" && "$file" == "MainDirectory" ]]; then 
	# 	cat $file/"${1}"/movies.txt | cut -d ";" -f1 $file/"${1}"/movies.txt  | sort
	# fi
		cat "${1}"/movies.txt | cut -d ";" -f1 "${1}"/movies.txt  | sort






	





