#!/bin/bash

found=0

for file in `ls`; do
	if [[ "$file" == "$1" ]]; then 
		cat "${1}"/movies.txt | cut -d ";" -f1 "${1}"/movies.txt | sort
		found=1
	fi
done

if (( $found == 0 )); then
	found=2
fi

	

	
	



