#!/bin/bash

# for file in ${*:2}; do 
	

# 	userFile=`echo $file | cut -d "/" -f2`
	
# 	if [[ -f "$file" && $file == *movies.txt ]]; then #checking to see if userFile
# 		everyonesMovies=`cat $file | cut -d ";" -f1`
# 		echo "$everyonesMovies"
# 		echo "END"
# 	fi 

# 	if [[ -d "$file" && $userFile != $1 ]]; then
# 		if [[ "$file" == "MainDirectory" ]]; then
# 			MainDirectory=$file
# 		fi
# 		echo "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
# 		source $0 "$1" $file/* 
# 	fi 

# 	if [[ -d "$file" && $userFile == $1 ]]; then
# 		if [[ "$file" == "MainDirectory" ]]; then
# 			MainDirectory=$file
# 		fi
# 		echo "ENTERING SPECIAL USER <DIREC></DIREC>TORY"
# 		source $0 "$1" $file/* 
# 		# echo "entering helper script"
# 		# source helper_script4 "$1" $file/*
# 	fi 


# done 



for file in `ls`; do 
  movieCount=0;

  if [[ "$file" != "$1" ]]; then
	while read line1; do

		

		while read line2; do

			if [[ "$line1" == "$line2" ]]; then
				let movieCount++;

				if (( $movieCount == 3 )); then
					echo $file
				fi
			fi

	    done < $file/movies.txt

	done < $1/movies.txt 
	
  fi

done 




