#!/bin/bash



for file in ${*:2}; do #run on all arguments starting from second argument

	if [[ -d "$file" && "$file" == "MainDirectory" ]]; then 	
		cat $file/"${1}"/movies.txt | cut -d ";" -f1 $file/"${1}"/movies.txt  | sort 
	fi

done 2> error.txt	 



	





