#!/bin/bash
	found=0
	for file in `ls`;do
		if [[ "$1" == "$file"  ]]; then
			found=1
		fi
	done

	if (( $found == 0 )); then
		found=2
	else		
	while read line; do
		genreOfMovie=`echo "$line" | cut -d";" -f3`
		nameofMovie=`echo "$line" | cut -d ";" -f1`
		yearofMovie=`echo "$line" | cut -d";" -f2`
		if [[ "$genreOfMovie" == "$2" ]]; then
		    numOfParam=`echo $#`
			if(( $numOfParam == 2 )); then
				echo "$nameofMovie"
			elif (( $yearofMovie >= $3 && $yearofMovie <= $4 )); then
					echo $nameofMovie
			fi
		fi
		
	done < "$1"/movies.txt | sort

         fi

